# This is the Jupyter notebook template for Assignment 3

First, we load the needed modules (feel free to add more as needed)

In [1]:
%matplotlib inline
# Allows viewing figures inline in the notebook
import numpy as np
# Numpy is a library for numerical computation
import matplotlib.pyplot as plt
# Matplotlib is a plotting library

### Template for Exercise 4: Gradient descent for the Netflix Problem
Below, you will first load and view the data, and then fill in:
* The template function **netflix_gradient**, which computes the gradient of E with respect to a and b
* The gradient descent template function **netflix**, where you only need to fill in:
    * the update step (initialization and convergence criteria are already taken care of)
    * the computation of the gradient magnitude
    * you may also want to play with the learning rate
* Note: You may want to implement additional functions for debugging purposes

Start out by loading and viewing the data

In [7]:
# Load and view the incomplete matrix
M = np.loadtxt('data/netflix_matrix.txt')
# Uncomment if you want to view it
print(M)

[[ 7.  8.  9.  0.  0.  1.  4.  2.  3.  9.]
 [ 0.  0. 10.  9. 10.  2.  3.  0.  0.  5.]
 [10.  9.  0.  8.  0.  0.  0.  2.  1.  3.]
 [ 1.  0.  2.  0.  0.  9.  8.  9.  0.  0.]
 [ 0.  1.  1.  0.  2.  0.  9.  0.  7.  0.]
 [ 2.  1.  0.  0.  1. 10.  0.  9.  0.  8.]]


In [1]:
def netflix_gradient(M, A, B):
    # This function is meant to compute the gradient of E with respect to A and B
    # Given: * the (6 x 10) numpy array M, whose 0 inputs you want to replace by predictions, 
    #          and whose nonzero inputs you want to preserve
    #        * two variable numpy arrays A (of size 6 x 2) and B (of size 2 x 10), 
    #          over which you want to optimize to reconstruct the matrix M as well as possible as a product A*B.
    # Return: The gradients grad_A and grad_B of the cost function E from the exercise, 
    #         with respect to a and b, respectively. They should have the same shape as a and b.
    I = (M > 0) * 1
    grad_A = 2*I*(-M+S@B)@(B.T)
    
    return grad_A, grad_B

In [12]:
def netflix(M):
    # A template function for performing gradient descent over A and B to minimize E
    # Input: The matrix M to be approximated
    people,movies = M.shape
    
    # Initialize at random
    np.random.seed(1) # Fixed seed for reproducibility; please don't change
    A = np.random.randn(people,2)
    B = np.random.randn(2,movies)
    
    # Set learning rate (you may want to play with this)
    learningrate = 0.00001
    
    # Setting parameters for convergence check
    num_iter = 1                   # This is the variable that will keep track of the number of iterations
    convergence = 0                # This is the variable that will keep track of whether we have converged
    max_iter = 10000               # We stop the algorithm after this many iterations
    tolerance = 0.01               # We conclude convergence when the magnitude of the gradient
                                   # is less than the tolerance
    
    while convergence == 0:
        ####################### MISSING PART ############## 
        # Compute gradient and take a step in the direction it dictates
        
        
        
        ####################### MISSING PART ##############        
        # Check for convergence -- you need to fill in the computation of the norm of the gradient at the current location
        num_iter = num_iter + 1      
        #cur_grad_norm = ##### MISSING
        
        if cur_grad_norm < tolerance:
            convergence = 1
            print('converged')
        elif num_iter > max_iter:
            convergence = 1 
            print('reached maximum nr of iterations')
    
    return A, B

Next, run your code to return your resulting A, B and A*B, and compare it with M